/* Global modal photo */

export const SET_PHOTO_RECORDS = 'SET_PHOTO_RECORDS'
export const SET_PHOTO_FILTER_TITLE = 'SET_PHOTO_FILTER_TITLE'
export const SET_PHOTO_FILTER_ALBUMID = 'SET_PHOTO_FILTER_ALBUMID'
